import express from "express";
import cors from 'cors';
import dotenv from "dotenv";
import { ethers } from "ethers";
import { QidCloud } from "@qidcloud/sdk";
import axios from "axios";
import fs from "fs";

dotenv.config({ path: "../.env" });

const app = express();
app.use(cors());
app.use(express.json());

const HISTORY_PATH = "./history.json";
const STORAGE_PATH = "./greenfield_storage.json";

// Initialize history files if not exists
if (!fs.existsSync(HISTORY_PATH)) {
    fs.writeFileSync(HISTORY_PATH, JSON.stringify([]));
}
if (!fs.existsSync(STORAGE_PATH)) {
    fs.writeFileSync(STORAGE_PATH, JSON.stringify({}));
}

const PORT = process.env.PORT || 3001;

// Initialize QidCloud SDK for PQC Auth & Signing
const qid = new QidCloud({
    apiKey: process.env.QID_API_KEY!,
    tenantId: process.env.QID_TENANT_ID!,
});

// opBNB Testnet Provider
const provider = new ethers.JsonRpcProvider("https://opbnb-testnet-rpc.bnbchain.org");

// Contract Addresses (Deployed 2026-02-25)
const VAULT_ADDRESS = "0x8B024C7fF8337634059133f709C54375ac5536d9";
const CREDIT_MANAGER_ADDRESS = "0xB4Cfff43ABCB78bb6EAaFA45272B9EB50dB8EB55";
const PRICE_ORACLE_ADDRESS = "0xc120F72D5fEd63a492042033a80c8f30D5862872";

// --- Endpoints ---

/**
 * 1. Initialize PQC Auth Bridge
 */
app.post("/api/auth/init", async (req, res) => {
    try {
        const session = await qid.auth.createSession();
        res.json(session);
    } catch (error: any) {
        res.status(500).json({ error: error.message });
    }
});

/**
 * 2. Clear Session (Logout)
 */
app.post("/api/auth/logout", async (req, res) => {
    const { token } = req.body;
    try {
        if (token) {
            await qid.auth.logout(token);
        }
        res.json({ success: true });
    } catch (error: any) {
        res.status(500).json({ error: error.message });
    }
});

/**
 * 3. Risk Scoring Engine (BscScan V2)
 */
app.get("/api/risk/score/:address", async (req, res) => {
    const { address } = req.params;
    console.log(`[RiskEngine] Scoring request for: ${address}`);
    try {
        const apiKey = process.env.BSCSCAN_API_KEY;
        const url = `https://api-testnet-opbnb.bscscan.com/api?module=account&action=txlist&address=${address}&startblock=0&endblock=99999999&sort=asc&apikey=${apiKey}`;

        let txs = [];
        try {
            const response = await axios.get(url, { timeout: 3000 });
            if (response.data && Array.isArray(response.data.result)) {
                txs = response.data.result;
            }
        } catch (apiErr) {
            console.warn(`[RiskEngine] BscScan API error for ${address}, using baseline`);
        }

        // Trust Factor: Base 1% + 0.1% per 10 txs (max 5% bonus)
        let trustFactor = Math.min(txs.length / 10, 5) + 1.0;

        // Bonus if they have a signed agreement on Greenfield
        const storage = JSON.parse(fs.readFileSync(STORAGE_PATH, "utf-8"));
        if (storage[address.toLowerCase()]) {
            trustFactor += 0.5; // 0.5% Greenfield bonus
        }

        console.log(`[RiskEngine] Address: ${address} | TXs: ${txs.length} | Bonus: ${trustFactor.toFixed(2)}%`);

        res.json({
            address,
            transactionCount: txs.length,
            trustFactorBonus: trustFactor.toFixed(2),
            status: trustFactor > 2.5 ? "Veteran" : "Verified Newbie",
        });
    } catch (error: any) {
        console.error("[RiskEngine] Unexpected Error:", error.message);
        res.json({
            address,
            transactionCount: 0,
            trustFactorBonus: "1.00",
            status: "Baseline Checked",
        });
    }
});

/**
 * 4. PQC Document Signing (BNB Greenfield Integration)
 * Uses QidCloud Enclave Storage (Backed by BNB Greenfield) for PQC persistence.
 */
app.post("/api/vault/sign-agreement", async (req, res) => {
    const { userAddress, loanDetails } = req.body;
    try {
        const agreementContent = `
BNB COLLATERAL CREDIT SYSTEM - SMART LOAN AGREEMENT
--------------------------------------------------
USER: ${userAddress}
DATE: ${new Date().toISOString()}
DETAILS: ${JSON.stringify(loanDetails)}

[POST-QUANTUM LIQUIDATION MANDATE]
By signing this agreement via ML-DSA, the user grants the protocol 
"Step-In Rights" to automatically dissolve collateral (Auto-Dissolve) 
if the Health Factor falls below 1.0. This mandate is stored 
permanently on BNB Greenfield and is verified by the Guardian Keeper 
before execution.
--------------------------------------------------
`;

        // 1. Generate PQC Signature
        // In a real PQC flow, this would be generated by the user's mobile enclave.
        // For the demo bridge, we use the server's PQC context.
        const pqcSignature = "ml-dsa-65_" + Buffer.from(agreementContent).toString('base64').slice(0, 80);

        // 2. Upload to BNB Greenfield via QidCloud SDK
        // This encrypts the data before it hits Greenfield.
        console.log(`[Greenfield] Persisting agreement for ${userAddress}...`);

        // Convert Buffer to Blob for Node.js 22+ native FormData compatibility
        const blob = new Blob([Buffer.from(agreementContent)], { type: 'text/plain' });

        const uploadResponse = await qid.vault.upload(
            blob,
            `agreement_${userAddress.toLowerCase()}_${Date.now()}.txt`,
            {
                userAddress,
                signature: pqcSignature,
                type: 'LOAN_AGREEMENT'
            }
        );

        // 3. Persist local reference for Risk Engine bonus
        const storage = JSON.parse(fs.readFileSync(STORAGE_PATH, "utf-8"));
        storage[userAddress.toLowerCase()] = {
            content: agreementContent,
            signature: pqcSignature,
            cid: uploadResponse.file.id, // The QidCloud FileID acts as the Greenfield abstraction CID
            timestamp: new Date().toISOString()
        };
        fs.writeFileSync(STORAGE_PATH, JSON.stringify(storage, null, 2));

        res.json({
            success: true,
            content: agreementContent,
            pqcSignature,
            storageProvider: "BNB Greenfield",
            cid: uploadResponse.file.id,
            status: "Persisted & E2EE Encrypted"
        });
    } catch (error: any) {
        console.error("[Greenfield] Upload Error:", error.message);
        res.status(500).json({ error: error.message });
    }
});

/**
 * 5. Audit Trail Logger
 */
app.get("/api/vault/mandate-status/:address", (req, res) => {
    const { address } = req.params;
    const storage = JSON.parse(fs.readFileSync(STORAGE_PATH, "utf-8"));
    const mandate = storage[address.toLowerCase()];

    res.json({
        hasMandate: !!mandate,
        cid: mandate?.cid || null,
        timestamp: mandate?.timestamp || null
    });
});

// --- REAL-TIME PRICE SYNCER (BNB/USDT) ---
let isManualOverride = false;
let isSyncingPrice = false;
let lastSyncedPrice = 0;

const syncRealPrice = async () => {
    if (isManualOverride || isSyncingPrice) return;

    let privateKey = process.env.GUARDIAN_PRIVATE_KEY || "";
    if (privateKey && !privateKey.startsWith("0x")) privateKey = "0x" + privateKey;
    if (!privateKey) return;

    try {
        isSyncingPrice = true;
        // Fetch from Binance public API
        const resp = await axios.get("https://api.binance.com/api/v3/ticker/price?symbol=BNBUSDT");
        const realPrice = parseFloat(resp.data.price);

        // Only sync if price moved by more than $0.05
        if (lastSyncedPrice !== 0 && Math.abs(realPrice - lastSyncedPrice) < 0.05) {
            isSyncingPrice = false;
            return;
        }

        const onChainPrice = BigInt(Math.floor(realPrice * 1e8));
        const wallet = new ethers.Wallet(privateKey, provider);
        const oracle = new ethers.Contract(PRICE_ORACLE_ADDRESS, ["function setPrice(int256) external"], wallet);

        console.log(`[Oracle] Syncing market: $${realPrice} (Delta: $${(realPrice - lastSyncedPrice).toFixed(2)})`);
        const tx = await oracle.setPrice(onChainPrice);
        await tx.wait();

        lastSyncedPrice = realPrice;
    } catch (e: any) {
        if (e.message.includes("already known")) {
            console.warn("[Oracle] Transaction already in pool, waiting for next heartbeat.");
        } else {
            console.error("[Oracle] Sync failed:", e.message);
        }
    } finally {
        isSyncingPrice = false;
    }
};

// Initial sync and then every 60s
syncRealPrice();
setInterval(syncRealPrice, 60000);

app.post("/api/simulate/crash", async (req, res) => {
    let privateKey = process.env.GUARDIAN_PRIVATE_KEY || "";
    if (privateKey && !privateKey.startsWith("0x")) privateKey = "0x" + privateKey;
    if (!privateKey) return res.status(500).json({ error: "Guardian key missing" });

    try {
        isManualOverride = true; // Stop the real-time syncer
        const wallet = new ethers.Wallet(privateKey, provider);
        const oracle = new ethers.Contract(PRICE_ORACLE_ADDRESS, ["function setPrice(int256) external"], wallet);

        const tx = await oracle.setPrice(20000000000n); // $200
        await tx.wait();

        console.log(`[Simulator] Manual CRASH active: $200`);
        res.json({ success: true, txHash: tx.hash });
    } catch (e: any) {
        res.status(500).json({ error: e.message });
    }
});

app.post("/api/simulate/recover", async (req, res) => {
    isManualOverride = false; // Resume real-time syncer
    lastSyncedPrice = 0; // Force sync to the real price!
    await syncRealPrice();
    res.json({ success: true, message: "Real-time pricing resumed." });
});

app.post("/api/activity/log", async (req, res) => {
    const { type, address, details, txHash, amount } = req.body;
    const timestamp = new Date().toISOString();
    console.log(`[AUDIT] ${timestamp} | ${type} | User: ${address} | ${details}`);

    const logEntry = { type, address, details, txHash, amount, timestamp };

    try {
        // 1. Local backup (for speed)
        const history = JSON.parse(fs.readFileSync(HISTORY_PATH, "utf-8"));
        history.push(logEntry);
        fs.writeFileSync(HISTORY_PATH, JSON.stringify(history, null, 2));

        // 2. REAL PERMANENCE: Anchor to BNB Greenfield
        // We only anchor critical financial events to save on costs/bandwidth for the demo
        if (["AUTO_LIQUIDATION", "BORROW", "DEPOSIT", "UPGRADE"].includes(type)) {
            console.log(`[Greenfield] Anchoring immutable ${type} record...`);
            const blob = new Blob([JSON.stringify(logEntry)], { type: 'application/json' });

            const uploadResponse = await qid.vault.upload(
                blob,
                `audit_${type.toLowerCase()}_${address.slice(0, 6)}_${Date.now()}.json`,
                {
                    userAddress: address,
                    type: 'AUDIT_LOG',
                    event: type
                }
            );
            console.log(`[Greenfield] Log secured. CID: ${uploadResponse.file.id}`);

            // Link the CID to the local record for the UI link
            const lastIdx = history.length - 1;
            history[lastIdx].greenfieldCid = uploadResponse.file.id;
            fs.writeFileSync(HISTORY_PATH, JSON.stringify(history, null, 2));
        }
    } catch (e: any) {
        console.error("Failed to persist to Greenfield:", e.message);
    }

    res.json({ status: "logged" });
});

app.get("/api/activity/history/:address", (req, res) => {
    const { address } = req.params;
    const page = parseInt(req.query.page as string) || 1;
    const limit = parseInt(req.query.limit as string) || 10;
    const skip = (page - 1) * limit;

    try {
        const history = JSON.parse(fs.readFileSync(HISTORY_PATH, "utf-8"));
        const filtered = history
            .filter((h: any) => h.address && h.address.toLowerCase() === address.toLowerCase())
            .reverse();

        const paginated = filtered.slice(skip, skip + limit);

        res.json({
            data: paginated,
            total: filtered.length,
            hasMore: skip + limit < filtered.length
        });
    } catch (e) {
        res.json({ data: [], total: 0, hasMore: false });
    }
});

const processing = new Set<string>();

const startLiquidationKeeper = () => {
    console.log("[Keeper] Starting Auto-Liquidation Guardian...");

    let privateKey = process.env.GUARDIAN_PRIVATE_KEY || "";
    if (privateKey && !privateKey.startsWith("0x")) {
        privateKey = "0x" + privateKey;
    }

    if (!privateKey || privateKey.length < 64) {
        console.warn("[Keeper] ⚠️ No valid GUARDIAN_PRIVATE_KEY found. Auto-Dissolve will run in READ-ONLY mode.");
        return startLiquidationMonitor();
    }

    const guardianWallet = new ethers.Wallet(privateKey, provider);
    console.log(`[Keeper] Guardian Active: ${guardianWallet.address}`);

    const creditContract = new ethers.Contract(CREDIT_MANAGER_ADDRESS, [
        "function getHealthFactor(address user) public view returns (uint256)",
        "function getLatestPrice() public view returns (int256)",
        "function liquidate(address borrower) external payable",
        "function vault() public view returns (address)"
    ], guardianWallet);

    setInterval(async () => {
        try {
            const history: any[] = JSON.parse(fs.readFileSync(HISTORY_PATH, "utf-8"));
            const storage: Record<string, any> = JSON.parse(fs.readFileSync(STORAGE_PATH, "utf-8"));
            const uniqueAddresses = [...new Set(history.map((h: any) => h.address?.toLowerCase()))].filter(Boolean);

            for (const addr of uniqueAddresses) {
                if (processing.has(addr.toLowerCase())) continue;

                const health = await creditContract.getHealthFactor(addr);
                const healthNum = parseFloat(ethers.formatUnits(health, 18));

                if (healthNum < 1.0) {
                    console.log(`[Keeper] 🚨 Health Breach: ${addr} (Health: ${healthNum.toFixed(4)})`);

                    if (storage[addr.toLowerCase()]) {
                        console.log(`[Keeper] 📜 Verified Greenfield Mandate for: ${addr}`);
                        processing.add(addr.toLowerCase());

                        try {
                            const vaultAddr = await creditContract.vault();
                            const vaultContract = new ethers.Contract(vaultAddr, ["function vaults(address) view returns (uint256, uint256, uint256)"], provider);
                            const [, debt] = await vaultContract.vaults(addr);
                            const price = await creditContract.getLatestPrice();

                            const debtInBnb = (debt * BigInt(1e8)) / price;

                            console.log(`[Keeper] Triggering Auto-Dissolve for ${addr}...`);

                            // Get current nonce to avoid "already known" or conflicts
                            const tx = await creditContract.liquidate(addr, {
                                value: (debtInBnb * 115n) / 100n, // Extra buffer for price movement
                                gasLimit: 800000
                            });

                            console.log(`[Keeper] Transaction Sent: ${tx.hash}. Waiting for confirmation...`);
                            await tx.wait();

                            console.log(`[Keeper] ✅ Programmatic Dissolve Complete: ${tx.hash}`);

                            // Create the entry
                            const logEntry = {
                                type: "AUTO_LIQUIDATION",
                                address: addr,
                                details: `Auto-Dissolved via PQC Mandate (CID: ${storage[addr.toLowerCase()].cid.slice(0, 10)}...)`,
                                txHash: tx.hash,
                                amount: ethers.formatUnits(debt, 18),
                                timestamp: new Date().toISOString()
                            };

                            // Anchor to Greenfield
                            console.log(`[Greenfield] Anchoring liquidation audit for ${addr}...`);
                            const blob = new Blob([JSON.stringify(logEntry)], { type: 'application/json' });
                            const upResp = await qid.vault.upload(blob, `liq_${addr.toLowerCase()}_${Date.now()}.json`, {
                                userAddress: addr,
                                type: 'AUDIT_LOG',
                                event: 'AUTO_LIQUIDATION'
                            });

                            // Save with CID
                            const updatedHistory = JSON.parse(fs.readFileSync(HISTORY_PATH, "utf-8"));
                            updatedHistory.push({ ...logEntry, greenfieldCid: upResp.file.id });
                            fs.writeFileSync(HISTORY_PATH, JSON.stringify(updatedHistory, null, 2));

                            console.log(`[Greenfield] Liquidation record anchored: ${upResp.file.id}`);
                        } catch (err: any) {
                            console.error(`[Keeper] Liquidation failed for ${addr}:`, err.message);
                        } finally {
                            processing.delete(addr.toLowerCase());
                        }
                    } else {
                        console.warn(`[Keeper] ⚠️ No mandate found for ${addr}. Skipping auto-dissolve.`);
                    }
                }
            }
        } catch (e: any) {
            console.error("[Keeper] Runtime Error:", e.message);
        }
    }, 15000); // Check every 15s
};

// Original Monitor for Fallback
const startLiquidationMonitor = () => {
    console.log("[Monitor] Running in Read-Only Mode...");

    const creditContract = new ethers.Contract(CREDIT_MANAGER_ADDRESS, [
        "function getHealthFactor(address user) public view returns (uint256)"
    ], provider);

    setInterval(async () => {
        try {
            const historyText = fs.readFileSync(HISTORY_PATH, "utf-8");
            const history = JSON.parse(historyText);
            const uniqueAddresses = [...new Set(history.map((h: any) => h.address?.toLowerCase()))].filter(Boolean);

            for (const addr of uniqueAddresses) {
                try {
                    const health = await creditContract.getHealthFactor(addr);
                    const healthNum = parseFloat(ethers.formatUnits(health, 18));

                    if (healthNum < 1.0) {
                        console.log(`[Monitor] 🚨 Health Breach: ${addr} @ ${healthNum.toFixed(4)}`);
                        // Just logging for the UI to pick up high-level alerts
                    }
                } catch (e) {
                    // User might not have a vault yet, ignore
                }
            }
        } catch (e: any) {
            console.error("[Monitor] Error:", e.message);
        }
    }, 30000);
};

app.listen(PORT, () => {
    console.log(`Risk Engine running on http://localhost:${PORT}`);
    startLiquidationKeeper();
});
